# Generated by Django 5.2.4 on 2025-07-26 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_subscription"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="payment_url",
            field=models.URLField(
                blank=True, null=True, verbose_name="Ссылка на оплату"
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="stripe_session_id",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="ID сессии Stripe"
            ),
        ),
    ]
