# Generated by Django 5.2.4 on 2025-07-26 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_payment_payment_url_payment_stripe_session_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="payment_method",
            field=models.CharField(
                choices=[
                    ("stripe", "Перевод с карты через Stripe"),
                    ("cash", "Наличные"),
                    ("transfer", "Перевод на счёт"),
                ],
                max_length=10,
                verbose_name="Способ оплаты",
            ),
        ),
    ]
