# Generated by Django 5.2.4 on 2025-07-26 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_alter_payment_payment_method"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="stripe_session_id",
            field=models.CharField(
                blank=True, max_length=500, null=True, verbose_name="ID сессии Stripe"
            ),
        ),
    ]
