# Generated by Django 5.2.4 on 2025-07-26 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0007_alter_payment_stripe_session_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="payment_url",
            field=models.URLField(
                blank=True, max_length=500, null=True, verbose_name="Ссылка на оплату"
            ),
        ),
    ]
