# Generated by Django 5.2.4 on 2025-07-26 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("materials", "0004_lesson_owner"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="price",
            field=models.DecimalField(decimal_places=2, default=200, max_digits=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="lesson",
            name="price",
            field=models.DecimalField(decimal_places=2, default=200, max_digits=8),
            preserve_default=False,
        ),
    ]
